.nh
.TH "MAKNOON" "1" "Jan 2024" "Maknoon Post-Quantum Engine" "Maknoon Manual"

.SH NAME
maknoon-config-set - Update a configuration setting


.SH SYNOPSIS
\fBmaknoon config set [key] [value] [flags]\fP


.SH DESCRIPTION
Update a configuration setting.
Keys:
  default_identity   - Default identity name
  security.time      - Argon2id iterations
  security.memory    - Argon2id memory (KB)
  security.threads   - Argon2id threads
  perf.concurrency   - Default parallel workers
  perf.stealth       - Default stealth mode (true/false)
  agent.max_memory   - Agent RAM limit (KB)
  agent.max_workers  - Agent CPU worker limit
  agent.allowed_urls - Comma-separated list of permitted servers
  audit.enabled      - Toggle forensic auditing (true/false)
  audit.logfile      - Path to structured JSON audit log
  paths.keys         - Custom keys directory
  paths.vaults       - Custom vaults directory
  gov.require_signed - Require signed policies (true/false)
  gov.auth_key       - Path to authorized governance public key


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for set


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--fips\fP[=false]
	Enforce strict FIPS-140 compliant cryptographic standards

.PP
\fB--json\fP[=false]
	Output results in JSON format

.PP
\fB--passphrase-file\fP=""
	Read passphrase from a file instead of prompting (use - for stdin). Also settable via MAKNOON_PASSPHRASE_FILE

.PP
\fB--policy\fP=""
	Path to a declarative governance policy file (JSON)

.PP
\fB--tpm\fP[=false]
	Enable TPM 2.0 hardware-backed storage for keys

.PP
\fB--tpm-device\fP="/dev/tpmrm0"
	Path to the TPM device node

.PP
\fB--tpm-pcrs\fP=[]
	List of PCRs to bind keys to (e.g., 7,14)

.PP
\fB--trace\fP[=false]
	Enable low-level diagnostic tracing to stderr


.SH SEE ALSO
\fBmaknoon-config(1)\fP


.SH HISTORY
1-Jan-2024 Auto generated by spf13/cobra
