.nh
.TH "MAKNOON" "1" "May 2026" "Maknoon Post-Quantum Engine" "Maknoon Manual"

.SH NAME
maknoon-fragment - Split a file into erasure-coded fragments [EXPERIMENTAL]


.SH SYNOPSIS
\fBmaknoon fragment [file] [flags]\fP


.SH DESCRIPTION
Breaks a file into redundant shards using Reed-Solomon erasure coding.
The original data can be reconstructed from any subset of size >= threshold.

.PP
NOTE: Fragment dispersal is experimental. Without a storage backend, shards
require manual placement. For production use, combine with an object store.


.SH OPTIONS
\fB-d\fP, \fB--data\fP=5
	Number of data shards

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for fragment

.PP
\fB-o\fP, \fB--output\fP=""
	Output directory for fragments

.PP
\fB-r\fP, \fB--parity\fP=3
	Number of parity shards (redundancy)

.PP
\fB-s\fP, \fB--passphrase\fP=""
	Passphrase for the signing key

.PP
\fB--sign-with\fP=""
	ML-DSA private key to sign each fragment block


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--fips\fP[=false]
	Enforce strict FIPS-140 compliant cryptographic standards

.PP
\fB--json\fP[=false]
	Output results in JSON format

.PP
\fB--policy\fP=""
	Path to a declarative governance policy file (JSON)

.PP
\fB--tpm\fP[=false]
	Enable TPM 2.0 hardware-backed storage for keys

.PP
\fB--tpm-device\fP="/dev/tpmrm0"
	Path to the TPM device node

.PP
\fB--tpm-pcrs\fP=[]
	List of PCRs to bind keys to (e.g., 7,14)

.PP
\fB--trace\fP[=false]
	Enable low-level diagnostic tracing to stderr


.SH SEE ALSO
\fBmaknoon(1)\fP


.SH HISTORY
19-May-2026 Auto generated by spf13/cobra
