.nh
.TH "MAKNOON" "1" "Jan 2024" "Maknoon Post-Quantum Engine" "Maknoon Manual"

.SH NAME
maknoon-keygen - Generate a Post-Quantum (KEM & SIG) identity


.SH SYNOPSIS
\fBmaknoon keygen [flags]\fP


.SH DESCRIPTION
Generate a Post-Quantum (KEM & SIG) identity


.SH OPTIONS
\fB--argon-mem\fP=65536
	Argon2id memory in KB

.PP
\fB--argon-threads\fP=4
	Argon2id parallel threads

.PP
\fB--argon-time\fP=3
	Argon2id iterations

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for keygen

.PP
\fB-n\fP, \fB--no-password\fP[=false]
	Generate unprotected keys (automation mode)

.PP
\fB-o\fP, \fB--output\fP=""
	Base name or path for the keys

.PP
\fB-s\fP, \fB--passphrase\fP=""
	Passphrase to protect the keys

.PP
\fB--profile\fP="nist"
	Cryptographic profile (nist, conservative)

.PP
\fB--profile-file\fP=""
	Path to a custom profile JSON file to protect the keys

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress informational output

.PP
\fB--rotate\fP=""
	Rotate: securely shred old identity [name] and replace with newly generated keys


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--fips\fP[=false]
	Enforce strict FIPS-140 compliant cryptographic standards

.PP
\fB--json\fP[=false]
	Output results in JSON format

.PP
\fB--passphrase-file\fP=""
	Read passphrase from a file instead of prompting (use - for stdin). Also settable via MAKNOON_PASSPHRASE_FILE

.PP
\fB--policy\fP=""
	Path to a declarative governance policy file (JSON)

.PP
\fB--tpm\fP[=false]
	Enable TPM 2.0 hardware-backed storage for keys

.PP
\fB--tpm-device\fP="/dev/tpmrm0"
	Path to the TPM device node

.PP
\fB--tpm-pcrs\fP=[]
	List of PCRs to bind keys to (e.g., 7,14)

.PP
\fB--trace\fP[=false]
	Enable low-level diagnostic tracing to stderr


.SH SEE ALSO
\fBmaknoon(1)\fP


.SH HISTORY
1-Jan-2024 Auto generated by spf13/cobra
