package crypto

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/viper"
)

func FuzzStreamEncryptDecrypt(f *testing.F) {
	f.Add([]byte("my-secret-key-123"), []byte("Hello, World!"), byte(0))
	f.Add([]byte("short"), []byte(""), byte(0))
	f.Add([]byte(""), []byte("data"), byte(1))

	f.Fuzz(func(t *testing.T, password []byte, data []byte, flags byte) {
		// Limit data size to avoid OOM in fuzzing (e.g., 1MB max)
		if len(data) > 1024*1024 {
			return
		}

		var encrypted bytes.Buffer
		err := EncryptStream(bytes.NewReader(data), &encrypted, password, flags, 2, 0)
		if err != nil {
			return // Expected failure for invalid flags/passwords generated by fuzzer
		}

		stealth := flags&FlagStealth != 0
		var decrypted bytes.Buffer
		_, resFlags, err := DecryptStream(bytes.NewReader(encrypted.Bytes()), &decrypted, password, 2, stealth)
		if err != nil {
			t.Fatalf("Failed to decrypt valid ciphertext: %v", err)
		}

		if resFlags != flags {
			t.Errorf("Flags mismatch. Got %d, want %d", resFlags, flags)
		}

		if !bytes.Equal(data, decrypted.Bytes()) {
			t.Errorf("Data mismatch. Got %q, want %q", decrypted.Bytes(), data)
		}
	})
}

func FuzzUnpackDynamicProfile(f *testing.F) {
	// Provide seeds representing valid-ish packed profiles
	f.Add(byte(128), []byte{1, 0, 1, 16, 4, 16, 12})
	f.Add(byte(200), []byte{0, 0, 0, 0, 0, 0, 0})

	f.Fuzz(func(t *testing.T, id byte, packed []byte) {
		if len(packed) < 7 {
			return // Ignore inputs that are too short to be parsed
		}
		dp, err := UnpackDynamicProfile(id, packed)
		if err != nil {
			return // Expected error on malformed data
		}

		// If unpacked successfully, validation shouldn't panic
		_ = dp.Validate()
	})
}

func FuzzRandomProfiles(f *testing.F) {
	f.Add(byte(100))
	f.Add(byte(200))

	f.Fuzz(func(t *testing.T, id byte) {
		dp := GenerateRandomProfile(id)
		if err := dp.Validate(); err != nil {
			t.Fatalf("Random profile validation failed: %v", err)
		}

		canary := []byte("fuzz-test-canary-data")
		pass := []byte("fuzz-pass")
		salt := make([]byte, dp.SaltSize())

		// Test Symmetric Roundtrip
		var encrypted bytes.Buffer
		key := dp.DeriveKey(pass, salt)
		aead, err := dp.NewAEAD(key)
		if err != nil {
			t.Fatalf("Failed to create AEAD: %v", err)
		}
		nonce := make([]byte, aead.NonceSize())

		// streamEncrypt/Decrypt now expect *EngineContext as the last argument
		if err := streamEncrypt(bytes.NewReader(canary), &encrypted, aead, nonce, 1, nil); err != nil {
			t.Fatalf("Encryption failed: %v", err)
		}

		var decrypted bytes.Buffer
		if err := streamDecrypt(bytes.NewReader(encrypted.Bytes()), &decrypted, aead, nonce, 1, nil); err != nil {
			t.Fatalf("Decryption failed: %v", err)
		}

		if !bytes.Equal(canary, decrypted.Bytes()) {
			t.Error("Data corruption detected")
		}
	})
}

func FuzzConfigJSON(f *testing.F) {
	f.Add([]byte(`{"default_identity": "test", "security": {"argon_time": 5}}`))
	f.Add([]byte(`{invalid-json`))

	f.Fuzz(func(t *testing.T, data []byte) {
		conf := DefaultConfig()
		// Test JSON unmarshaling directly first
		_ = json.Unmarshal(data, conf)
		_ = conf.Validate()

		// Test file-based loading with Viper
		tmpFile := filepath.Join(t.TempDir(), "config.json")
		if err := os.WriteFile(tmpFile, data, 0600); err != nil {
			t.Fatal(err)
		}

		v := viper.New()
		v.SetConfigFile(tmpFile)
		if err := v.ReadInConfig(); err == nil {
			_ = v.Unmarshal(conf)
		}
	})
}

func FuzzKeyManager(f *testing.F) {
	f.Add("my-id", []byte("raw-key-data"))

	f.Fuzz(func(t *testing.T, name string, keyData []byte) {
		if name == "" || strings.Contains(name, "..") || strings.Contains(name, "/") {
			return
		}

		tmpDir := t.TempDir()
		im := &IdentityManager{KeysDir: tmpDir}

		// Write garbage key files
		_ = os.WriteFile(filepath.Join(tmpDir, name+".kem.key"), keyData, 0600)
		_ = os.WriteFile(filepath.Join(tmpDir, name+".kem.pub"), keyData, 0644)

		// Attempt to resolve and load
		_ = im.ResolveKeyPath(name, "")
		_, _, _ = im.ResolveBaseKeyPath(name)
		_, _ = im.LoadIdentity(name, []byte("pass"), "", false)
	})
}
