package crypto

import (
	"bytes"
	"testing"
)

func FuzzStreamEncryptDecrypt(f *testing.F) {
	f.Add([]byte("my-secret-key-123"), []byte("Hello, World!"), byte(0))
	f.Add([]byte("short"), []byte(""), byte(0))
	f.Add([]byte(""), []byte("data"), byte(1))

	f.Fuzz(func(t *testing.T, password []byte, data []byte, flags byte) {
		// Limit data size to avoid OOM in fuzzing (e.g., 1MB max)
		if len(data) > 1024*1024 {
			return
		}

		var encrypted bytes.Buffer
		err := EncryptStream(bytes.NewReader(data), &encrypted, password, flags, 2, 0)
		if err != nil {
			return // Expected failure for invalid flags/passwords generated by fuzzer
		}

		var decrypted bytes.Buffer
		resFlags, _, err := DecryptStream(bytes.NewReader(encrypted.Bytes()), &decrypted, password, 2, false)
		if err != nil {
			t.Fatalf("Failed to decrypt valid ciphertext: %v", err)
		}

		if resFlags != flags {
			t.Errorf("Flags mismatch. Got %d, want %d", resFlags, flags)
		}

		if !bytes.Equal(data, decrypted.Bytes()) {
			t.Errorf("Data mismatch. Got %q, want %q", decrypted.Bytes(), data)
		}
	})
}

func FuzzUnpackDynamicProfile(f *testing.F) {
	// Provide seeds representing valid-ish packed profiles
	f.Add(byte(128), []byte{1, 0, 1, 16, 4, 16, 12})
	f.Add(byte(200), []byte{0, 0, 0, 0, 0, 0, 0})

	f.Fuzz(func(t *testing.T, id byte, packed []byte) {
		if len(packed) < 7 {
			return // Ignore inputs that are too short to be parsed
		}
		dp, err := UnpackDynamicProfile(id, packed)
		if err != nil {
			return // Expected error on malformed data
		}

		// If unpacked successfully, validation shouldn't panic
		_ = dp.Validate()
	})
}
